server:
  port: 8096
spring:
  application:
    name: "ShippingReport"
  devtools:
    add-properties: false

  profiles:
    include: null
  datasource:
    url: "jdbc:sqlserver://jitsolutionssql.database.windows.net:1433;database=svdi-05;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30"
    username: "james@jitsolutionssql"
    password: "Jjcq0517*"
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
      databasePlatform: "org.hibernate.dialect.SQLServer2012Dialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
aws:
  secretsmanager:
    endpoint: secretsmanager.us-east-1.amazonaws.com
    region: us-east-1
  credentials:
    access-key: "AKIAYBQ7YL5JOYZ6YXJ3"
    secret-key: "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"
  region:
    static: us-east-1
  stack:
    auto: false
