server:
  port: 8096
spring:
  application:
    name: "ShippingReport"
  devtools:
    add-properties: false

  profiles:
    include: null
  datasource:
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
      databasePlatform: "org.hibernate.dialect.SQLServer2012Dialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
aws:
  secretsmanager:
    secretname: "arn:aws:secretsmanager:us-east-1:553043648338:secret:prod/AppDocker/MsSqlServer-5oLQmc"
    region: us-east-1
  credentials:
    access-key: "AKIAYBQ7YL5JOYZ6YXJ3"
    secret-key: "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"
  region:
    static: us-east-1
  stack:
    auto: false
